name: Trigger auto deployment for gauk-container-app-deploy-test

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/gauk-container-app-deploy-test-AutoDeployTrigger-10d3c434-744a-49c3-b333-0719da27e90a.yml'

  # Allow mannually trigger 
  workflow_dispatch:      

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to container registry
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.GAUKCONTAINERAPPDEPLOYTEST_REGISTRY_USERNAME }}
          password: ${{ secrets.GAUKCONTAINERAPPDEPLOYTEST_REGISTRY_PASSWORD }}

      - name: Build and push container image to registry
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: gkgaurav31/gauk-container-app-deploy-test:7d918633c03b2c08d730c9bef587941eb2c86b52
          file: ./Dockerfile
          context: ./


  deploy:
    runs-on: ubuntu-latest
    needs: build
    
    steps:
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.GAUKCONTAINERAPPDEPLOYTEST_AZURE_CREDENTIALS }}


      - name: Deploy to containerapp
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az config set extension.use_dynamic_install=yes_without_prompt
            az containerapp registry set -n gauk-container-app-deploy-test -g REPRO-RG --server index.docker.io --username  ${{ secrets.GAUKCONTAINERAPPDEPLOYTEST_REGISTRY_USERNAME }} --password ${{ secrets.GAUKCONTAINERAPPDEPLOYTEST_REGISTRY_PASSWORD }}
            az containerapp update -n gauk-container-app-deploy-test -g REPRO-RG --image ${{ secrets.GAUKCONTAINERAPPDEPLOYTEST_REGISTRY_USERNAME }}/gauk-container-app-deploy-test:7d918633c03b2c08d730c9bef587941eb2c86b52
